# Generated by Django 5.1.3 on 2024-12-02 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0002_auto_20211109_1456"),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_shifts",
                        to="fleet.bus",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_shifts",
                        to="fleet.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus shift",
                "verbose_name_plural": "Bus shifts",
            },
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_time",
                    models.TimeField(verbose_name="time of arrival/departure"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "bus_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops",
                        to="operation.busshift",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_stops",
                        to="geography.place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus stop",
                "verbose_name_plural": "Bus stops",
                "ordering": ["order", "schedule_time"],
                "unique_together": {("place", "bus_shift", "schedule_time")},
            },
        ),
    ]
